Repository jupyterlab/galata, pull requests merged in 2021-07, with the labels that each got.

#70 Add jlpm build step to readme
  README.md
Labels: documentation

#72 Add check release workflow on CI and CHANGELOG.md
  .github/workflows/check-release.yml
  .github/workflows/main.yml
  CHANGELOG.md
  README.md
  RELEASE.md
  lerna.json
  package.json
  packages/galata-example/package.json
  packages/galata/package.json
Labels: maintenance

#66 fix remote connection to chromium browser
  packages/galata/jest-env.js
  packages/galata/jest-setup.js
  packages/galata/jest-teardown.js
Labels: bug
